#!/usr/bin/perl -s

use Data::Dumper;

my $user = $u;

use warnings;
use strict;

my $config = {
    'sj' => { 
        shell => '/bin/tcsh'
    }
};

my $imagename = shift @ARGV;
die "Must specify imagename" if ! defined $imagename;

my $dirname = $imagename;

if (! defined $user) {
    $user = 'user';
}
else {
    $imagename = $user . '-' . $imagename;
}

my $shell = $config->{$user}{shell} || '/bin/bash';
my $dotfiles = "dotfiles.$user";

if (! -d "$dirname/$dotfiles") {
    die "$dotfiles does not exist";
}

open my $docker_file_template, "<", "$dirname/Dockerfile.tmpl" or die $!;
open my $docker_file,          ">", "$dirname/Dockerfile"      or die $!;

while (<$docker_file_template>) {
    s/{{user}}/$user/g;
    s#{{shell}}#$shell#g;
    print $docker_file $_;
}

close $docker_file_template;
close $docker_file;

#
# TODO implement tagging
#
##if [ ! -z $3 ]; then
##    tag=:$3
##fi

#
# TODO parameterize "from" lines in dependent docker files
#
my $cmd = qq(docker build -t $imagename $dirname);
warn $cmd;
system($cmd);


# 
# TODO add repo name
#
##docker build -t sjfloat/${name}$tag $name
