#!/bin/sh

name=$1
user=`docker inspect -f '{{.Config.User}}' $name`

echo $name | grep exercism > /dev/null

if [ $? = 0 ]; then
    hvolume=exercism-work
    dir=exercism
else
    hvolume=${name}-work
    dir=$hvolume
    if [ ! -d $hvolume ]; then
        mkdir $hvolume
    fi
fi


docker create -it \
    --name $name \
    -v `pwd`/${hvolume}:/home/${user}/${dir} \
    $name
