
from debian:jessie

env DEBIAN_FRONTEND noninteractive

run apt-get update && apt-get install -y \
    ctags \
    curl \
    git \
    htop \
    make \
    man \
    sudo \
    tcsh \
    tmux \
    tree \
    vim \
    vim-doc \
    wget

run apt-get clean
run rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

env USER steve
run adduser $USER
user $USER

env HOME /home/$USER
workdir $HOME

add vimrc $HOME/.vimrc
add vim $HOME/.vim
add tcshrc $HOME/.tcshrc
add cshrc $HOME/.cshrc
add exrc $HOME/.exrc
add inputrc $HOME/.inputrc
add tmux.conf $HOME/.tmux.conf

env SHELL /bin/tcsh

user root
run chown -R ${USER}: $HOME
run chsh -s $SHELL $USER

run echo "$USER  ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER

user $USER

cmd $SHELL
